---
dist: xenial

sudo: required

language: java

jdk: openjdk8

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.m2

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - mvn clean package 
