oracle:
  url: "jdbc:oracle:thin:@acme.com:1521:sid"
  username: "te"
  password: "password"

spring:
  jackson:
    default-property-inclusion: non_null
  boot:
    admin:
      client:
        url: http://localhost:9000
        username: "admin"               #These two are needed so that the client
        password: "password"            #can register at the protected server api
        instance:
          metadata:
            user.name: "jsmith"         #These two are needed so that the server
            user.password: "password"   #can access the protected client endpoints

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  packages-to-scan: "acme.twitter.controller"
  paths-to-match: "/api/**"
